// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { HealthHealthGetData, HealthHealthGetResponses, SetupFrameworkApiV1FrameworksSetupPostData, SetupFrameworkApiV1FrameworksSetupPostErrors, SetupFrameworkApiV1FrameworksSetupPostResponses, SubmitEvaluationApiV1EvaluationsSubmitPostData, SubmitEvaluationApiV1EvaluationsSubmitPostErrors, SubmitEvaluationApiV1EvaluationsSubmitPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Basic health check.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Setup Framework
 *
 * Setup a new framework by extracting controls from multiple PDFs.
 * Each PDF has a section name; controls are saved as config/frameworks/{framework_name}/{section_name}.json.
 * Send section_names as one string: comma-separated names, one per file, in the same order as files.
 */
export const setupFrameworkApiV1FrameworksSetupPost = <ThrowOnError extends boolean = false>(options: Options<SetupFrameworkApiV1FrameworksSetupPostData, ThrowOnError>) => (options.client ?? client).post<SetupFrameworkApiV1FrameworksSetupPostResponses, SetupFrameworkApiV1FrameworksSetupPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/frameworks/setup',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Submit Evaluation
 *
 * Submit an evaluation: files + framework name. Each file has its own control_ids field
 * (control_ids_1 for file 1, control_ids_2 for file 2, etc.). Each value = comma-separated IDs.
 * Returns DB-mimic JSON + evaluation_id + report_path.
 */
export const submitEvaluationApiV1EvaluationsSubmitPost = <ThrowOnError extends boolean = false>(options: Options<SubmitEvaluationApiV1EvaluationsSubmitPostData, ThrowOnError>) => (options.client ?? client).post<SubmitEvaluationApiV1EvaluationsSubmitPostResponses, SubmitEvaluationApiV1EvaluationsSubmitPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/evaluations/submit',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
