// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_setup_framework_api_v1_frameworks_setup_post
 */
export type BodySetupFrameworkApiV1FrameworksSetupPost = {
    /**
     * Framework Name
     *
     * Framework identifier
     */
    framework_name: string;
    /**
     * Section Names
     *
     * Comma-separated section names (one per PDF, same order as files). Example: policies,procedures,controls
     */
    section_names: string;
    /**
     * Files
     *
     * PDF files (same order as section_names)
     */
    files: Array<Blob | File>;
};

/**
 * Body_submit_evaluation_api_v1_evaluations_submit_post
 */
export type BodySubmitEvaluationApiV1EvaluationsSubmitPost = {
    /**
     * Framework Name
     *
     * Framework identifier (e.g. NDI)
     */
    framework_name: string;
    /**
     * Files
     *
     * Files (PDF, DOCX, PPTX, CSV, XLSX); 1 or more
     */
    files: Array<Blob | File>;
    /**
     * Control Ids 1
     *
     * Comma-separated control IDs for file 1
     */
    control_ids_1?: string;
    /**
     * Control Ids 2
     *
     * Comma-separated control IDs for file 2
     */
    control_ids_2?: string;
    /**
     * Control Ids 3
     *
     * Comma-separated control IDs for file 3
     */
    control_ids_3?: string;
    /**
     * Control Ids 4
     *
     * Comma-separated control IDs for file 4
     */
    control_ids_4?: string;
    /**
     * Control Ids 5
     *
     * Comma-separated control IDs for file 5
     */
    control_ids_5?: string;
    /**
     * Control Ids 6
     *
     * Comma-separated control IDs for file 6
     */
    control_ids_6?: string;
    /**
     * Control Ids 7
     *
     * Comma-separated control IDs for file 7
     */
    control_ids_7?: string;
    /**
     * Control Ids 8
     *
     * Comma-separated control IDs for file 8
     */
    control_ids_8?: string;
    /**
     * Control Ids 9
     *
     * Comma-separated control IDs for file 9
     */
    control_ids_9?: string;
    /**
     * Control Ids 10
     *
     * Comma-separated control IDs for file 10
     */
    control_ids_10?: string;
    /**
     * Control Ids 11
     *
     * Comma-separated control IDs for file 11
     */
    control_ids_11?: string;
    /**
     * Control Ids 12
     *
     * Comma-separated control IDs for file 12
     */
    control_ids_12?: string;
    /**
     * Control Ids 13
     *
     * Comma-separated control IDs for file 13
     */
    control_ids_13?: string;
    /**
     * Control Ids 14
     *
     * Comma-separated control IDs for file 14
     */
    control_ids_14?: string;
    /**
     * Control Ids 15
     *
     * Comma-separated control IDs for file 15
     */
    control_ids_15?: string;
    /**
     * Control Ids 16
     *
     * Comma-separated control IDs for file 16
     */
    control_ids_16?: string;
    /**
     * Control Ids 17
     *
     * Comma-separated control IDs for file 17
     */
    control_ids_17?: string;
    /**
     * Control Ids 18
     *
     * Comma-separated control IDs for file 18
     */
    control_ids_18?: string;
    /**
     * Control Ids 19
     *
     * Comma-separated control IDs for file 19
     */
    control_ids_19?: string;
    /**
     * Control Ids 20
     *
     * Comma-separated control IDs for file 20
     */
    control_ids_20?: string;
};

/**
 * ControlSummary
 *
 * Summary of extracted controls for one section (PDF).
 */
export type ControlSummary = {
    /**
     * Section Name
     *
     * Name of the section (PDF)
     */
    section_name: string;
    /**
     * Controls Count
     *
     * Number of controls extracted
     */
    controls_count: number;
    /**
     * Json Path
     *
     * Relative path to the saved JSON file
     */
    json_path: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SetupFrameworkResponse
 *
 * Response after successfully setting up a framework from multiple PDFs.
 */
export type SetupFrameworkResponse = {
    /**
     * Framework Name
     *
     * Framework identifier
     */
    framework_name: string;
    /**
     * Total Controls
     *
     * Total controls across all sections
     */
    total_controls: number;
    /**
     * Sections
     *
     * Per-section summary
     */
    sections?: Array<ControlSummary>;
    /**
     * Created At
     *
     * When the setup completed
     */
    created_at?: string;
};

/**
 * SubmitEvaluationResponse
 *
 * Response after submitting an evaluation (15 files + framework).
 */
export type SubmitEvaluationResponse = {
    /**
     * Evaluation Id
     *
     * Unique evaluation run ID
     */
    evaluation_id: string;
    /**
     * Mimic Json
     *
     * DB-mimic: framework_name -> field_1..field_15 -> comma-separated control IDs
     */
    mimic_json: {
        [key: string]: unknown;
    };
    /**
     * Report Path
     *
     * Path to the generated report PDF
     */
    report_path?: string;
    /**
     * File Evaluations
     *
     * Per-file assessment results
     */
    file_evaluations?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type SetupFrameworkApiV1FrameworksSetupPostData = {
    body: BodySetupFrameworkApiV1FrameworksSetupPost;
    path?: never;
    query?: never;
    url: '/api/v1/frameworks/setup';
};

export type SetupFrameworkApiV1FrameworksSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetupFrameworkApiV1FrameworksSetupPostError = SetupFrameworkApiV1FrameworksSetupPostErrors[keyof SetupFrameworkApiV1FrameworksSetupPostErrors];

export type SetupFrameworkApiV1FrameworksSetupPostResponses = {
    /**
     * Successful Response
     */
    200: SetupFrameworkResponse;
};

export type SetupFrameworkApiV1FrameworksSetupPostResponse = SetupFrameworkApiV1FrameworksSetupPostResponses[keyof SetupFrameworkApiV1FrameworksSetupPostResponses];

export type SubmitEvaluationApiV1EvaluationsSubmitPostData = {
    body: BodySubmitEvaluationApiV1EvaluationsSubmitPost;
    path?: never;
    query?: never;
    url: '/api/v1/evaluations/submit';
};

export type SubmitEvaluationApiV1EvaluationsSubmitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitEvaluationApiV1EvaluationsSubmitPostError = SubmitEvaluationApiV1EvaluationsSubmitPostErrors[keyof SubmitEvaluationApiV1EvaluationsSubmitPostErrors];

export type SubmitEvaluationApiV1EvaluationsSubmitPostResponses = {
    /**
     * Successful Response
     */
    200: SubmitEvaluationResponse;
};

export type SubmitEvaluationApiV1EvaluationsSubmitPostResponse = SubmitEvaluationApiV1EvaluationsSubmitPostResponses[keyof SubmitEvaluationApiV1EvaluationsSubmitPostResponses];
